### ISSUE TITLE
`a` is Converted to `1000`?

### ISSUE THREAD

**Issue by HoldOffHunger** [wimulkeman/PHP_Braille_converter#1]
Hi!

I'm not sure I 'm doing this right.  But I'm only getting 1s and 0s as a result from the Braille Handler.

Working demo online: https://3v4l.org/pJvft

**Comment by wimulkeman** [comment]
Hello @HoldOffHunger 

That is the correct response from the handler. Unfortunate the documentation is in Dutch, but the idea behind it is the following:

The code returns a bit notation which maps to the braille dots. For example the character n has the following dot notation in Braille.
```
o o
- o
o -
```
which maps to the bit notation 
```
32 16         o o        
 8  4    >    - o    >    56    >   110110 (bit notation)
 2  1         o -        
```
The value `110110` will be returned by the handler. The fronted maps this to a table which display a yellow square for the `1` characters and a grey square for the `0` characters.

I would do the bit encoding part different these days, but the idea behind it still works 🙂.
